[package]
name = "tuist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
crossterm = "0.27.0"
ratatui = "0.26.1"
reqwest = {version = "0.11.24", features = ["blocking"]}
